'use strict';
// Fit & Leicht – eingebaute Daten (funktionieren offline).
// Nährwerte sind gerundete Durchschnittswerte; Etiketten einzelner Produkte können abweichen.

window.FL_DATA = (function () {
  // [Name, Kategorie, kcal pro 100 g/ml, Eiweiß g pro 100 g/ml, Portion in g/ml, Portionsname]
  const FOODS = [
    // Frühstück & Brot
    ['Haferflocken', 'Frühstück & Brot', 372, 13.5, 50, '5 EL'],
    ['Porridge mit Milch', 'Frühstück & Brot', 100, 4.5, 300, 'Schale'],
    ['Müsli (ohne Zucker)', 'Frühstück & Brot', 360, 10, 60, 'Schale'],
    ['Cornflakes', 'Frühstück & Brot', 375, 7, 30, 'Portion'],
    ['Vollkornbrot', 'Frühstück & Brot', 220, 7.5, 50, 'Scheibe'],
    ['Mischbrot', 'Frühstück & Brot', 240, 7, 50, 'Scheibe'],
    ['Toastbrot', 'Frühstück & Brot', 260, 8, 25, 'Scheibe'],
    ['Brötchen', 'Frühstück & Brot', 270, 9, 55, 'Stück'],
    ['Vollkornbrötchen', 'Frühstück & Brot', 240, 9, 60, 'Stück'],
    ['Laugenbrezel', 'Frühstück & Brot', 270, 8, 85, 'Stück'],
    ['Croissant', 'Frühstück & Brot', 410, 8, 60, 'Stück'],
    ['Knäckebrot', 'Frühstück & Brot', 340, 10, 10, 'Scheibe'],
    ['Reiswaffel', 'Frühstück & Brot', 390, 8, 8, 'Stück'],
    ['Pfannkuchen', 'Frühstück & Brot', 220, 7, 120, 'Stück'],
    ['Butter', 'Frühstück & Brot', 740, 0.7, 10, 'Portion'],
    ['Marmelade', 'Frühstück & Brot', 250, 0.4, 20, '1 EL'],
    ['Honig', 'Frühstück & Brot', 305, 0.4, 20, '1 EL'],
    ['Nuss-Nougat-Creme', 'Frühstück & Brot', 540, 6, 20, '1 EL'],
    ['Erdnussbutter', 'Frühstück & Brot', 600, 25, 15, '1 EL'],
    ['Ei, gekocht', 'Frühstück & Brot', 155, 13, 60, 'Stück'],
    ['Spiegelei', 'Frühstück & Brot', 200, 13.5, 60, 'Stück'],
    ['Rührei', 'Frühstück & Brot', 170, 11, 130, 'Portion (2 Eier)'],
    ['Omelett mit Käse', 'Frühstück & Brot', 180, 13, 200, 'Portion'],

    // Milchprodukte
    ['Milch 1,5 %', 'Milch & Käse', 47, 3.4, 200, 'Glas'],
    ['Milch 3,5 %', 'Milch & Käse', 64, 3.3, 200, 'Glas'],
    ['Haferdrink', 'Milch & Käse', 45, 0.5, 200, 'Glas'],
    ['Naturjoghurt 1,5 %', 'Milch & Käse', 47, 4, 150, 'Becher'],
    ['Griechischer Joghurt', 'Milch & Käse', 120, 5, 150, 'Becher'],
    ['Skyr', 'Milch & Käse', 63, 11, 150, 'Becher'],
    ['Magerquark', 'Milch & Käse', 67, 12, 250, 'Becher'],
    ['Quark 20 %', 'Milch & Käse', 110, 12.5, 125, 'Portion'],
    ['Hüttenkäse', 'Milch & Käse', 100, 12, 200, 'Becher'],
    ['Proteinpudding', 'Milch & Käse', 75, 10, 200, 'Becher'],
    ['Gouda', 'Milch & Käse', 360, 25, 30, 'Scheibe'],
    ['Emmentaler', 'Milch & Käse', 380, 28, 30, 'Scheibe'],
    ['Mozzarella', 'Milch & Käse', 250, 18, 125, 'Kugel'],
    ['Feta', 'Milch & Käse', 260, 17, 50, 'Portion'],
    ['Frischkäse', 'Milch & Käse', 250, 5.5, 30, 'Portion'],
    ['Frischkäse leicht', 'Milch & Käse', 150, 8, 30, 'Portion'],
    ['Schlagsahne', 'Milch & Käse', 310, 2.4, 30, '2 EL'],

    // Fleisch, Fisch & Eiweiß
    ['Hähnchenbrust, gebraten', 'Fleisch, Fisch & Eiweiß', 160, 30, 150, 'Filet'],
    ['Putenbrust, gebraten', 'Fleisch, Fisch & Eiweiß', 150, 29, 150, 'Filet'],
    ['Hackfleisch gemischt', 'Fleisch, Fisch & Eiweiß', 260, 20, 125, 'Portion'],
    ['Rindersteak', 'Fleisch, Fisch & Eiweiß', 190, 28, 200, 'Steak'],
    ['Schnitzel, paniert', 'Fleisch, Fisch & Eiweiß', 240, 18, 180, 'Stück'],
    ['Bratwurst', 'Fleisch, Fisch & Eiweiß', 300, 13, 100, 'Stück'],
    ['Salami', 'Fleisch, Fisch & Eiweiß', 400, 22, 20, '4 Scheiben'],
    ['Kochschinken', 'Fleisch, Fisch & Eiweiß', 110, 19, 30, '2 Scheiben'],
    ['Putenaufschnitt', 'Fleisch, Fisch & Eiweiß', 100, 20, 30, '2 Scheiben'],
    ['Lachs, gebraten', 'Fleisch, Fisch & Eiweiß', 210, 22, 125, 'Filet'],
    ['Thunfisch im eigenen Saft', 'Fleisch, Fisch & Eiweiß', 110, 25, 130, 'Dose'],
    ['Fischstäbchen', 'Fleisch, Fisch & Eiweiß', 190, 12, 120, '4 Stück'],
    ['Garnelen', 'Fleisch, Fisch & Eiweiß', 90, 19, 100, 'Portion'],
    ['Tofu natur', 'Fleisch, Fisch & Eiweiß', 130, 14, 150, 'Portion'],
    ['Linsen, gekocht', 'Fleisch, Fisch & Eiweiß', 115, 9, 200, 'Portion'],
    ['Kichererbsen, gekocht', 'Fleisch, Fisch & Eiweiß', 130, 7, 200, 'Portion'],
    ['Kidneybohnen', 'Fleisch, Fisch & Eiweiß', 100, 7, 200, 'Portion'],
    ['Proteinpulver', 'Fleisch, Fisch & Eiweiß', 380, 75, 30, 'Messlöffel'],

    // Beilagen
    ['Reis, gekocht', 'Beilagen', 130, 2.7, 200, 'Portion'],
    ['Vollkornreis, gekocht', 'Beilagen', 120, 2.8, 200, 'Portion'],
    ['Nudeln, gekocht', 'Beilagen', 150, 5.5, 250, 'Portion'],
    ['Vollkornnudeln, gekocht', 'Beilagen', 140, 6, 250, 'Portion'],
    ['Kartoffeln, gekocht', 'Beilagen', 72, 2, 250, 'Portion'],
    ['Bratkartoffeln', 'Beilagen', 150, 2.5, 200, 'Portion'],
    ['Kartoffelpüree', 'Beilagen', 100, 2, 200, 'Portion'],
    ['Pommes frites', 'Beilagen', 290, 3.5, 150, 'Portion'],
    ['Süßkartoffel, gebacken', 'Beilagen', 90, 2, 200, 'Portion'],
    ['Couscous, gekocht', 'Beilagen', 110, 3.8, 200, 'Portion'],
    ['Quinoa, gekocht', 'Beilagen', 120, 4.4, 180, 'Portion'],

    // Gemüse & Salat
    ['Brokkoli', 'Gemüse & Salat', 35, 3, 200, 'Portion'],
    ['Blumenkohl', 'Gemüse & Salat', 25, 2, 200, 'Portion'],
    ['Möhre', 'Gemüse & Salat', 40, 0.9, 100, 'Stück'],
    ['Gurke', 'Gemüse & Salat', 13, 0.6, 200, 'halbe Gurke'],
    ['Tomate', 'Gemüse & Salat', 18, 0.9, 100, 'Stück'],
    ['Paprika', 'Gemüse & Salat', 30, 1, 150, 'Stück'],
    ['Blattsalat, gemischt', 'Gemüse & Salat', 18, 1.3, 100, 'Schüssel'],
    ['Spinat', 'Gemüse & Salat', 23, 2.9, 150, 'Portion'],
    ['Zucchini', 'Gemüse & Salat', 20, 1.5, 200, 'Portion'],
    ['Champignons', 'Gemüse & Salat', 22, 3, 150, 'Portion'],
    ['Erbsen', 'Gemüse & Salat', 80, 5, 150, 'Portion'],
    ['Mais', 'Gemüse & Salat', 85, 3, 100, 'Portion'],
    ['Avocado', 'Gemüse & Salat', 160, 2, 100, 'halbe'],
    ['Gemüsepfanne', 'Gemüse & Salat', 70, 2.5, 350, 'Portion'],
    ['Dressing (Essig & Öl)', 'Gemüse & Salat', 300, 0.3, 30, '2 EL'],
    ['Olivenöl', 'Gemüse & Salat', 880, 0, 10, '1 EL'],

    // Obst
    ['Apfel', 'Obst', 52, 0.3, 150, 'Stück'],
    ['Banane', 'Obst', 89, 1.1, 120, 'Stück'],
    ['Birne', 'Obst', 57, 0.4, 160, 'Stück'],
    ['Orange', 'Obst', 47, 0.9, 150, 'Stück'],
    ['Mandarine', 'Obst', 53, 0.8, 70, 'Stück'],
    ['Erdbeeren', 'Obst', 32, 0.7, 150, 'Schale'],
    ['Heidelbeeren', 'Obst', 57, 0.7, 125, 'Schale'],
    ['Himbeeren', 'Obst', 45, 1.2, 125, 'Schale'],
    ['Weintrauben', 'Obst', 69, 0.7, 150, 'Schale'],
    ['Kiwi', 'Obst', 61, 1.1, 75, 'Stück'],
    ['Ananas', 'Obst', 50, 0.5, 150, 'Portion'],
    ['Mango', 'Obst', 60, 0.8, 150, 'Portion'],
    ['Wassermelone', 'Obst', 30, 0.6, 300, 'Stück'],

    // Snacks & Süßes
    ['Mandeln', 'Snacks & Süßes', 600, 21, 30, 'Handvoll'],
    ['Walnüsse', 'Snacks & Süßes', 690, 15, 30, 'Handvoll'],
    ['Erdnüsse, geröstet', 'Snacks & Süßes', 590, 25, 30, 'Handvoll'],
    ['Studentenfutter', 'Snacks & Süßes', 480, 13, 30, 'Handvoll'],
    ['Proteinriegel', 'Snacks & Süßes', 360, 33, 60, 'Riegel'],
    ['Müsliriegel', 'Snacks & Süßes', 400, 6, 25, 'Riegel'],
    ['Vollmilchschokolade', 'Snacks & Süßes', 535, 7.5, 25, '4 Stück'],
    ['Zartbitterschokolade 70 %', 'Snacks & Süßes', 580, 8, 20, '3 Stück'],
    ['Gummibärchen', 'Snacks & Süßes', 343, 6.9, 30, 'Handvoll'],
    ['Kartoffelchips', 'Snacks & Süßes', 535, 6, 30, 'Handvoll'],
    ['Salzstangen', 'Snacks & Süßes', 375, 10, 30, 'Handvoll'],
    ['Popcorn, gesalzen', 'Snacks & Süßes', 460, 9, 25, 'Schale'],
    ['Butterkekse', 'Snacks & Süßes', 440, 7.5, 25, '4 Stück'],
    ['Rührkuchen', 'Snacks & Süßes', 390, 6, 80, 'Stück'],
    ['Käsekuchen', 'Snacks & Süßes', 260, 8, 120, 'Stück'],
    ['Berliner', 'Snacks & Süßes', 340, 6, 70, 'Stück'],
    ['Vanilleeis', 'Snacks & Süßes', 210, 3.5, 70, 'Kugel'],

    // Getränke
    ['Wasser', 'Getränke', 0, 0, 250, 'Glas'],
    ['Kaffee, schwarz', 'Getränke', 2, 0.2, 200, 'Tasse'],
    ['Cappuccino', 'Getränke', 37, 2, 200, 'Tasse'],
    ['Latte Macchiato', 'Getränke', 40, 2.4, 300, 'Glas'],
    ['Tee, ungesüßt', 'Getränke', 1, 0, 250, 'Tasse'],
    ['Orangensaft', 'Getränke', 45, 0.7, 200, 'Glas'],
    ['Apfelschorle', 'Getränke', 24, 0.1, 330, 'Glas'],
    ['Smoothie', 'Getränke', 55, 0.6, 250, 'Flasche'],
    ['Cola', 'Getränke', 42, 0, 330, 'Dose'],
    ['Cola Zero', 'Getränke', 0.3, 0, 330, 'Dose'],
    ['Limonade', 'Getränke', 40, 0, 330, 'Dose'],
    ['Eistee', 'Getränke', 30, 0, 330, 'Glas'],
    ['Energy Drink', 'Getränke', 46, 0, 250, 'Dose'],
    ['Bier', 'Getränke', 42, 0.5, 500, 'Flasche'],
    ['Alkoholfreies Bier', 'Getränke', 25, 0.4, 500, 'Flasche'],
    ['Radler', 'Getränke', 40, 0.3, 500, 'Flasche'],
    ['Weißwein', 'Getränke', 75, 0.1, 200, 'Glas'],
    ['Rotwein', 'Getränke', 85, 0.1, 200, 'Glas'],

    // Gerichte & Fast Food
    ['Pizza Margherita', 'Gerichte & Fast Food', 250, 10, 350, 'ganze Pizza'],
    ['Pizza Salami', 'Gerichte & Fast Food', 280, 11, 350, 'ganze Pizza'],
    ['Döner', 'Gerichte & Fast Food', 200, 11, 350, 'Stück'],
    ['Dürüm', 'Gerichte & Fast Food', 205, 11, 380, 'Stück'],
    ['Cheeseburger', 'Gerichte & Fast Food', 254, 13, 120, 'Stück'],
    ['Burger, groß', 'Gerichte & Fast Food', 250, 12, 220, 'Stück'],
    ['Currywurst mit Soße', 'Gerichte & Fast Food', 240, 10, 200, 'Portion'],
    ['Mayonnaise', 'Gerichte & Fast Food', 700, 1, 20, '1 EL'],
    ['Ketchup', 'Gerichte & Fast Food', 110, 1.2, 20, '1 EL'],
    ['Spaghetti Bolognese', 'Gerichte & Fast Food', 140, 7, 400, 'Teller'],
    ['Lasagne', 'Gerichte & Fast Food', 160, 8, 350, 'Portion'],
    ['Chili con Carne', 'Gerichte & Fast Food', 110, 8, 350, 'Teller'],
    ['Gulasch', 'Gerichte & Fast Food', 130, 12, 300, 'Portion'],
    ['Hähnchen-Curry mit Reis', 'Gerichte & Fast Food', 140, 8, 400, 'Teller'],
    ['Sushi (Maki)', 'Gerichte & Fast Food', 145, 5, 150, '6 Stück'],
    ['Caesar Salad', 'Gerichte & Fast Food', 150, 9, 300, 'Schüssel'],
    ['Bowl mit Hähnchen', 'Gerichte & Fast Food', 140, 9, 450, 'Schüssel'],
    ['Wrap mit Hähnchen', 'Gerichte & Fast Food', 200, 11, 250, 'Stück'],
    ['Belegtes Brötchen mit Käse', 'Gerichte & Fast Food', 255, 12, 110, 'Stück'],
    ['Tomatensuppe', 'Gerichte & Fast Food', 45, 1, 300, 'Teller'],
    ['Linseneintopf', 'Gerichte & Fast Food', 85, 5, 400, 'Teller']
  ].map(([name, cat, kcal, protein, portion, unit], i) => ({ id: 'db' + i, name, cat, kcal, protein, portion, unit }));

  const FOOD_CATS = ['Frühstück & Brot', 'Milch & Käse', 'Fleisch, Fisch & Eiweiß', 'Beilagen', 'Gemüse & Salat', 'Obst', 'Snacks & Süßes', 'Getränke', 'Gerichte & Fast Food'];

  // Übungen: Ablauf in Schritten, typische Fehler, leichter/schwerer. keys = Suchbegriffe für die Wochenpläne.
  const EXERCISES = [
    { id: 'squat', name: 'Kniebeugen', emoji: '🦵', muscles: 'Beine, Po', keys: ['kniebeuge'],
      steps: ['Füße schulterbreit, Zehen leicht nach außen.', 'Hüfte nach hinten schieben, als würdest du dich auf einen Stuhl setzen.', 'So tief gehen, wie es mit geradem Rücken geht (Oberschenkel etwa waagerecht).', 'Über die Fersen kraftvoll hochdrücken.'],
      tip: 'Knie zeigen in Richtung Zehen und fallen nicht nach innen. Brust bleibt oben.',
      easier: 'Auf einen Stuhl setzen und wieder aufstehen.', harder: 'Mit Rucksack oder Kurzhanteln, oder als Sprung-Kniebeuge.' },
    { id: 'pushup', name: 'Liegestütze', emoji: '💪', muscles: 'Brust, Schultern, Arme', keys: ['liegestütz'],
      steps: ['Hände etwas breiter als die Schultern aufsetzen.', 'Körper von Kopf bis Ferse in einer Linie, Bauch fest.', 'Langsam absenken, bis die Brust knapp über dem Boden ist.', 'Kontrolliert hochdrücken.'],
      tip: 'Hüfte nicht durchhängen lassen. Ellbogen etwa 45° vom Körper.',
      easier: 'An der Wand, an einer Tischkante oder auf den Knien.', harder: 'Füße erhöht oder langsam 3 Sekunden absenken.' },
    { id: 'lunge', name: 'Ausfallschritte', emoji: '🚶', muscles: 'Beine, Po', keys: ['ausfallschritt'],
      steps: ['Aufrecht stehen, Hände an die Hüfte.', 'Einen großen Schritt nach vorn machen.', 'Hinteres Knie Richtung Boden senken, beide Knie etwa 90°.', 'Über die vordere Ferse zurückdrücken, Seite wechseln.'],
      tip: 'Vorderes Knie bleibt über dem Fuß, nicht weit vor den Zehen.',
      easier: 'Kleinerer Schritt oder an einer Wand festhalten.', harder: 'Mit Gewichten oder als Gehende Ausfallschritte.' },
    { id: 'plank', name: 'Unterarmstütz (Plank)', emoji: '🧱', muscles: 'Bauch, Rumpf', keys: ['plank', 'unterarmstütz'],
      steps: ['Unterarme unter den Schultern aufsetzen.', 'Beine strecken, auf die Zehenspitzen.', 'Körper in einer Linie halten, Bauch und Po anspannen.', 'Ruhig weiteratmen und die Zeit halten.'],
      tip: 'Nicht ins Hohlkreuz fallen und den Po nicht zu hoch schieben.',
      easier: 'Knie auf dem Boden lassen.', harder: 'Abwechselnd ein Bein oder einen Arm anheben.' },
    { id: 'sideplank', name: 'Seitstütz', emoji: '📐', muscles: 'Seitliche Bauchmuskeln', keys: ['seitstütz'],
      steps: ['Seitlich auf einen Unterarm stützen, Ellbogen unter der Schulter.', 'Beine gestreckt übereinander.', 'Hüfte anheben, bis der Körper eine Linie bildet.', 'Halten, dann Seite wechseln.'],
      tip: 'Hüfte nicht absinken lassen.',
      easier: 'Unteres Knie auf dem Boden lassen.', harder: 'Oberes Bein anheben.' },
    { id: 'bridge', name: 'Glute Bridge', emoji: '🌉', muscles: 'Po, hintere Oberschenkel', keys: ['glute bridge', 'bridge'],
      steps: ['Auf den Rücken legen, Knie gebeugt, Füße hüftbreit.', 'Arme neben dem Körper.', 'Po anspannen und die Hüfte hochdrücken, bis Knie, Hüfte und Schultern eine Linie bilden.', 'Kurz halten, langsam absenken.'],
      tip: 'Die Kraft kommt aus dem Po, nicht aus dem unteren Rücken.',
      easier: 'Weniger hoch drücken.', harder: 'Auf einem Bein oder mit Gewicht auf der Hüfte.' },
    { id: 'row', name: 'Rudern', emoji: '🚣', muscles: 'Rücken, Bizeps', keys: ['rudern'],
      steps: ['Wasserflaschen oder Kurzhanteln in die Hände nehmen.', 'Oberkörper mit geradem Rücken etwa 45° nach vorn neigen.', 'Ellbogen eng am Körper nach hinten ziehen.', 'Schulterblätter zusammendrücken, langsam ablassen.'],
      tip: 'Nicht ins Hohlkreuz gehen und nicht mit Schwung arbeiten.',
      easier: 'Leichtere Flaschen oder einarmig mit Abstützen am Tisch.', harder: 'Schwerere Gewichte oder Widerstandsband.' },
    { id: 'climber', name: 'Mountain Climbers', emoji: '⛰️', muscles: 'Bauch, Schultern, Ausdauer', keys: ['mountain climber'],
      steps: ['In den Liegestütz mit gestreckten Armen gehen.', 'Ein Knie zur Brust ziehen.', 'Schnell die Beine wechseln, wie beim Laufen.', 'Hüfte bleibt tief und ruhig.'],
      tip: 'Schultern bleiben über den Händen.',
      easier: 'Langsam abwechselnd, Hände auf einer Bank.', harder: 'Schneller oder Knie diagonal zum Ellbogen.' },
    { id: 'burpee', name: 'Burpees', emoji: '🔥', muscles: 'Ganzkörper, Ausdauer', keys: ['burpee'],
      steps: ['Aus dem Stand in die Hocke gehen, Hände auf den Boden.', 'Beine nach hinten springen in den Liegestütz.', 'Füße wieder nach vorn springen.', 'Hochspringen und über dem Kopf klatschen.'],
      tip: 'Lieber sauber und langsamer als schnell und unsauber.',
      easier: 'Beine nacheinander zurücksetzen, ohne Sprung.', harder: 'Mit Liegestütz am Boden.' },
    { id: 'jacks', name: 'Hampelmann', emoji: '⭐', muscles: 'Ausdauer, Ganzkörper', keys: ['hampelmann', 'jumping jack'],
      steps: ['Aufrecht stehen, Arme seitlich.', 'Beine auseinander springen und Arme über den Kopf führen.', 'Zurück in die Ausgangsposition springen.', 'Locker im Rhythmus bleiben.'],
      tip: 'Leicht auf den Fußballen landen.',
      easier: 'Seitliche Schritte statt Sprünge.', harder: 'Schneller oder mit tiefer Hocke.' },
    { id: 'wallsit', name: 'Wandsitzen', emoji: '🪑', muscles: 'Oberschenkel', keys: ['wandsitz'],
      steps: ['Rücken an die Wand lehnen.', 'Füße etwa 50 cm vor die Wand setzen.', 'An der Wand runterrutschen, bis die Knie etwa 90° gebeugt sind.', 'Position halten.'],
      tip: 'Knie über den Knöcheln, Rücken flach an der Wand.',
      easier: 'Weniger tief gehen.', harder: 'Länger halten oder ein Gewicht auf die Oberschenkel.' },
    { id: 'press', name: 'Schulterdrücken', emoji: '🏋️', muscles: 'Schultern, Trizeps', keys: ['schulterdrück'],
      steps: ['Gewichte auf Schulterhöhe, Handflächen nach vorn.', 'Bauch anspannen.', 'Gewichte senkrecht über den Kopf drücken.', 'Langsam zurück auf Schulterhöhe.'],
      tip: 'Nicht ins Hohlkreuz drücken.',
      easier: 'Im Sitzen oder mit leichteren Gewichten.', harder: 'Einarmig oder schwerer.' },
    { id: 'jumpsquat', name: 'Jump Squats', emoji: '🦘', muscles: 'Beine, Ausdauer', keys: ['jump squat'],
      steps: ['Wie eine Kniebeuge nach unten gehen.', 'Explosiv nach oben springen.', 'Weich in die nächste Kniebeuge landen.'],
      tip: 'Leise landen, Knie nicht nach innen.',
      easier: 'Normale Kniebeugen mit Wadenheben oben.', harder: 'Höher springen oder Arme hinter dem Kopf.' },
    { id: 'split', name: 'Bulgarian Split Squats', emoji: '🛋️', muscles: 'Beine, Po', keys: ['split squat'],
      steps: ['Hinteren Fuß auf eine Bank oder einen Stuhl legen.', 'Vorderen Fuß weit genug vorn aufsetzen.', 'Hinteres Knie Richtung Boden senken.', 'Über die vordere Ferse hochdrücken.'],
      tip: 'Oberkörper leicht nach vorn, Gewicht auf dem vorderen Bein.',
      easier: 'Ohne Erhöhung als normaler Ausfallschritt.', harder: 'Mit Kurzhanteln.' },
    { id: 'calf', name: 'Wadenheben', emoji: '🦶', muscles: 'Waden', keys: ['wadenheben'],
      steps: ['Auf eine Stufe stellen, Fersen frei.', 'Langsam auf die Zehenspitzen drücken.', 'Kurz halten.', 'Langsam unter Stufenhöhe absenken.'],
      tip: 'Zum Gleichgewicht leicht festhalten.',
      easier: 'Auf flachem Boden.', harder: 'Einbeinig oder mit Gewicht.' },
    { id: 'deadlift', name: 'Kreuzheben', emoji: '🏗️', muscles: 'Rücken, Po, Beine', keys: ['kreuzheb'],
      steps: ['Gewicht vor den Schienbeinen, Füße hüftbreit.', 'Hüfte nach hinten, Rücken gerade, greifen.', 'Mit geradem Rücken aufrichten, Hüfte nach vorn schieben.', 'Kontrolliert wieder absenken.'],
      tip: 'Rücken nie rund machen. Gewicht nah am Körper führen.',
      easier: 'Mit leichtem Gewicht oder nur bis zum Knie.', harder: 'Schwerer oder einbeinig (rumänisch).' },
    { id: 'twist', name: 'Russian Twists', emoji: '🔄', muscles: 'Seitliche Bauchmuskeln', keys: ['russian twist'],
      steps: ['Hinsetzen, Knie gebeugt, Oberkörper leicht zurücklehnen.', 'Hände vor der Brust zusammen.', 'Oberkörper nach links drehen, dann nach rechts.', 'Bauch die ganze Zeit fest.'],
      tip: 'Die Drehung kommt aus dem Oberkörper, nicht nur aus den Armen.',
      easier: 'Füße auf dem Boden lassen.', harder: 'Füße anheben oder ein Gewicht halten.' },
    { id: 'legraise', name: 'Beinheben', emoji: '🦿', muscles: 'Unterer Bauch', keys: ['beinheben'],
      steps: ['Auf den Rücken legen, Hände unter den Po.', 'Beine gestreckt anheben, bis sie senkrecht sind.', 'Langsam absenken, ohne den Boden zu berühren.'],
      tip: 'Unterer Rücken bleibt am Boden.',
      easier: 'Mit gebeugten Knien.', harder: 'Langsamer absenken oder im Hang an der Stange.' },
    { id: 'knees', name: 'High Knees', emoji: '🏃', muscles: 'Ausdauer, Beine', keys: ['high knees'],
      steps: ['Auf der Stelle laufen.', 'Knie abwechselnd bis auf Hüfthöhe ziehen.', 'Arme mitschwingen.'],
      tip: 'Auf den Fußballen bleiben, aufrecht laufen.',
      easier: 'Auf der Stelle marschieren.', harder: 'Schneller oder mit 20 Sekunden Vollgas.' },
    { id: 'dips', name: 'Trizeps-Dips am Stuhl', emoji: '🪑', muscles: 'Trizeps, Schultern', keys: ['dips'],
      steps: ['Hände hinter dir auf die Stuhlkante, Finger nach vorn.', 'Beine nach vorn strecken oder anwinkeln.', 'Ellbogen nach hinten beugen und den Körper absenken.', 'Wieder hochdrücken.'],
      tip: 'Ellbogen zeigen nach hinten, nicht zur Seite. Stuhl gegen Wegrutschen sichern.',
      easier: 'Knie stärker beugen.', harder: 'Beine gestreckt oder erhöht.' }
  ];

  return { FOODS, FOOD_CATS, EXERCISES };
})();
